components/modules/alliance/alliance_admin/urls.py
from django.urls import path
from . import views

app_name = 'alliance_admin'

urlpatterns = [
    path('projects/<user>/<project>/alliance_admin/', views.index, name='index'),
    path('projects/<user>/<project>/alliance_admin/<str:uid>/logs', views.logs, name='logs'),
    path('projects/<user>/<project>/alliance_admin/create', views.create, name='create'),
    path('projects/<user>/<project>/alliance_admin/<str:uid>/details', views.details, name='details'),
    path('projects/<user>/<project>/alliance_admin/<int:id>/start', views.start, name='start'),
    path('projects/<user>/<project>/alliance_admin/<int:id>/stop', views.stop, name='stop'),
    path('projects/<user>/<project>/alliance_admin/<str:uid>/project', views.project, name='project'),
    path('projects/<user>/<project>/alliance_admin/<str:uid>/log', views.log, name='log'),

]

components/modules/alliance/alliance_admin/forms.py
from django import forms
from django.core.validators import RegexValidator


class AllianceInstanceForm(forms.Form):
    uid = forms.CharField(max_length=521)
    controller_url = forms.CharField(
        validators=[RegexValidator(regex='(http[s]?://)([a-zA-Z|0-9|-]+)([.][a-zA-Z]+)?', message='Not a valid URL')],
        max_length=512
    )
    orchestrator_url = forms.CharField(
        validators=[RegexValidator(regex='(http[s]?://)([a-zA-Z|0-9|-]+)([.][a-zA-Z]+)?', message='Not a valid URL')],
        max_length=512
    )
    orchestrator_status = forms.CharField(max_length=32)
    controller_port = forms.IntegerField()
    minio_port = forms.IntegerField()
    project = forms.CharField()
    seed_model = forms.CharField()
    orchestrator_algorithm = forms.CharField()

components/modules/alliance/alliance_admin/templates/alliance_admin.html
{% extends 'baseproject.html' %}
{% block content %}
<main role="main" class="col-md-7 col-rg-7 ">

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2>Alliance</h2>
        <div class="btn-toolbar mb-2 mb-md-0">
            <a href="{% url 'alliance_admin:create' request.user project.slug %}">
                <button id="create" class="btn btn-large btn-primary">Add new</button>
            </a>
        </div>
    </div>

    <div class="row">
        {% for alliance_instance in alliance_instances %}
        <div class="">
            <div class="card" style="min-width:600px; margin-bottom:15px;">
                <div class="card-body">
                    <h5 class="card-title">Alliance Model</h5>
                    <h6 class="card-title">ID: {{ alliance_instance.uid }}</h6>
                    {% if alliance_instance.orchestrator_status == 'running' %}

                    <div class="alert alert-success" role="alert">
                        <p class="card-text"> Orchestrator is: <b>{{ alliance_instance.orchestrator_status }}</b></p>
                    </div>
                    <a href="{% url 'alliance_admin:details' request.user project.slug alliance_instance.uid %}"
                       class="btn btn-info">Open</a>

                    {% elif alliance_instance.orchestrator_status == 'stopped' %}

                    <div class="alert alert-secondary" role="alert">
                        <p class="card-text"> Orchestrator is: <b>{{ alliance_instance.orchestrator_status }}</b></p>
                    </div>
                    <a href="{% url 'alliance_admin:details' request.user project.slug alliance_instance.uid %}"
                       class="btn btn-info">Open</a>


                    {% else %}

                    <div class="alert alert-secondary" role="alert">
                        <p class="card-text"> Orchestrator is: <b>{{ alliance_instance.orchestrator_status }}</b></p>
                    </div>
                    <a href="{% url 'alliance_admin:details' request.user project.slug alliance_instance.uid %}"
                       class="btn btn-info">Open</a>

                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</main>
{% endblock %}

components/modules/alliance/alliance_admin/templates/alliance_create.html
{% extends 'baseproject.html' %}
{% block content %}
<main role="main" class="col-md-7 col-rg-7 ">

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2>Alliance Admin</h2>

    </div>

    <div class="row">
        <form action="{% url 'alliance_admin:create' request.user project.slug %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="model">Start a alliance session</label>
                <label for="model">Seed Model</label>
                <select name="model" class="form-control">
                    {% for model in models %}
                    <option value="{{ model.uid }}">UID: {{ model.uid }} Name:{{ model.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

    </div>

</main>
{% endblock %}

components/modules/alliance/alliance_admin/templates/alliance_details.html
{% extends 'baseproject.html' %}
{% load static %}
{% block extrascripts %}

    <link rel="stylesheet" type="text/css" href="{% static 'dt/datatables.min.css' %}"/>

    <script type="text/javascript" src="{% static 'dt/datatables.min.js' %}"></script>

{% endblock %}
{% block content %}
<main role="main" class="col-md-7 col-rg-7">

    <nav aria-label="breadcrumb" style="padding-left: 5px; padding-top: 25px; padding-bottom: 25px;">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'alliance_admin:index' user project.slug %}">Alliance</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">{{ ai.uid }}</li>
        </ol>
    </nav>

    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="orchestrator-tab" data-toggle="tab" href="#orchestrator" role="tab"
               aria-controls="orchestrator"
               aria-selected="true">Settings</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="members-tab" data-toggle="tab" href="#members" role="tab" aria-controls="members"
               aria-selected="false">Members</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="logs-tab" data-toggle="tab" href="#logs" role="tab" aria-controls="logs"
               aria-selected="false">Logs</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="checkpoint-tab" data-toggle="tab" href="#checkpoint" role="tab" aria-controls="checkpoint"
               aria-selected="false">Checkpoints</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="orchestrator" role="tabpanel" aria-labelledby="orchestrator-tab">
            <div class="row">
                <div class="">
                    {% if ai.orchestrator_status == 'unconfigured' %}

                    <p style="margin-top:25px;margin-left:10px;">You need to configure the orchestrator before you start
                        it the first time.
                        Please, select a seed model and an algorithm below:</p>
                    <form method="POST" style="margin-left:10px;">
                        {% csrf_token %}

                        <div class="form-group row">
                            <label for="id_uid" class="col-sm-2 col-form-label">Alliance UID:</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control-plaintext" id="id_uid"
                                       value="{{ ai.uid }}" name="uid">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="id_controller_url" class="col-sm-2 col-form-label">Controller URL:</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control-plaintext" id="id_controller_url"
                                       value="{{ ai.controller_url }}" name="controller_url">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="id_orchestrator_status" class="col-sm-2 col-form-label">Status:</label>
                            <div class="col-sm-10">
                                <select class="form-control" id="id_orchestrator_status" name="orchestrator_status">
                                    <option value="stopped">stopped</option>
                                    <option value="running">running</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="id_controller_port" class="col-sm-2 col-form-label">Controller Port:</label>
                            <div class="col-sm-10">
                                <input type="text" readonly class="form-control-plaintext" id="id_controller_port"
                                       value="{{ ai.controller_port }}" name="controller_port">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="id_project" class="col-sm-2 col-form-label">Project</label>
                            <div class="col-sm-10">
                                <select class="form-control" id="id_project" name="project">
                                    <option value="{{ project.id }}">{{ project.name }}</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="id_orchestrator_algorithm" class="col-sm-2 col-form-label">Algorithm</label>
                            <div class="col-sm-10">
                                <select class="form-control" id="id_orchestrator_algorithm"
                                        name="orchestrator_algorithm">
                                    <option value="Federated Averaging">Federated Averaging</option>
                                    <option value="Custom">Custom</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="id_seed_model" class="col-sm-2 col-form-label">Seed Model</label>
                            <div class="col-sm-10">
                                <select class="form-control" id="id_seed_model" name="seed_model">
                                    {% for model in models %}
                                    <option value="{{ model.id }}">{{ model.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>

                    {% else %}

                    <div class="card" style="min-width:600px;margin-bottom:15px;margin-top:35px;">
                        <div class="card-body">
                            {% if ai.orchestrator_status == 'running' %}

                            <div class="alert alert-success" role="alert">
                                <p class="card-text"> Orchestrator is: {{ ai.orchestrator_status }}</p>
                            </div>

                            {% else %}

                            <div class="alert alert-secondary" role="alert">
                                <p class="card-text"> Orchestrator is: <b>{{ ai.orchestrator_status }}</b></p>
                            </div>

                            {% endif %}

                            <p class="card-text">
                                Controller URL: <b>{{ domain }}</b> Controller Port:
                                <b>{{ ai.controller_port }}</b>
                            </p>
                            <p class="card-text">S3 storage URL: <b>{{ project.slug }}-minio.{{domain }}</b> S3 Port:
                                <b>443</b></p>
                            <p class="card-text"> Created: <b>{{ ai.created_at }}</b></p>
                            <p class="card-text"> Updated: <b>{{ ai.updated_at }}</b></p>

                            {% if ai.orchestrator_status == 'running' %}

                            <a href="{% url 'alliance_admin:stop' request.user project.slug ai.id %}"
                               class="btn btn-danger">Stop</a>

                            {% else %}

                            <form action="{% url 'alliance_admin:start' request.user project.slug ai.id %}"
                                  method="post">
                                {% csrf_token %}

                                <div class="form-group">
                                    <label for="rounds">Rounds</label>
                                    <input name="rounds">
                                </div>

                                <button type="submit" class="btn btn-primary">Start</button>
                            </form>
                                <a href="{% url 'alliance_admin:project' request.user project.slug ai.uid %}" class="btn btn-secondary">Download Client Config</a>
                            {% endif %}
                        </div>
                    </div>

                    {% endif %}
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="members" role="tabpanel" aria-labelledby="members-tab">
            <div class="table-responsive" style="margin-bottom:15px;margin-top:35px;">
                <table class="table table-striped table-sm">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Status</th>
                        <th>Joined</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for member in members %}
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="tab-pane fade" id="checkpoint" role="tabpanel" aria-labelledby="checkpoint-tab">
            <div class="table-responsive" style="margin-bottom:15px;margin-top:35px;">
                {% for checkpoint in checkpoints %}
                {{ checkpoint }}
                {% endfor %}
                <table class="table table-striped table-sm">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Bucket</th>
                        <th>Name</th>
                        <th>Last Modified</th>
                        <th>eTag</th>
                        <th>Size</th>
                        <th>Content Type</th>
                        <th>Link</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in dtos %}
                    <tr>
                        <td></td>
                        <td>{{ obj.Bucket }}</td>
                        <td>{{ obj.Name }}</td>
                        <td>{{ obj.LastModified }}</td>
                        <td>{{ obj.ETag }}</td>
                        <td>{{ obj.Size }}</td>
                        <td>{{ obj.ContentType }}</td>
                        <td>
                            <a href="{{ obj.Link }}">Download</a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="tab-pane fade" id="logs" role="tabpanel" aria-labelledby="logs-tab">
            <div class="table-responsive" style="margin-bottom:15px;margin-top:35px;">
                <table id="logtable" class="table table-striped table-sm">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Created</th>
                        <th>Text</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for event in events %}
                    <tr>
                        <td>{{ event.id }}</td>
                        <td>{{ event.created_at }}</td>
                        <td>{{ event.text }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                                <script>$(document).ready(function () {
                    $('#logtable').DataTable();
                });</script>
            </div>
        </div>
    </div>
</main>
{% endblock %}

components/modules/alliance/alliance_admin/templates/event_log.html
{% extends 'baseproject.html' %}

{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2>Alliance - Event log</h2>
    </div>

    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th>#</th>
                <th>Client</th>
                <th>Command</th>
                <th>Payload</th>
                <th>More info</th>
            </tr>
            </thead>
            <tbody>
            {% for request in requests %}
            <tr>
                <td></td>
                <td>{{ request.client }}</td>
                <td>
                    {% if request.command == 0 %}
                    Connect
                    {% elif request.command == 1 %}
                    Train
                    {% elif request.command == 2 %}
                    Validate
                    {% elif request.command == 3 %}
                    Vote
                    {% elif request.command == 4 %}
                    GlobalModel
                    {% elif request.command == 5 %}
                    Model
                    {% elif request.command == 6 %}
                    Score
                    {% endif %}
                </td>
                <td>{{ request.payload }}</td>
                <td>{{ request.extra }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock %}